# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

cask "sonny-desktop" do
  version "0.11.29"
  sha256 "b7ad4218f487893d5e70154d895c5019ab2f3b4a5513979f7a43090ea99d8d44"

  url "https://downloads.codepros.org/sonny/0.11.29/sonny-desktop_0.11.29_darwin_universal.zip"
  name "Sonny"
  desc "Desktop app for the Sonny AI coding agent"
  homepage "https://codepros.org/"

  depends_on macos: ">= :big_sur"

  app "Sonny.app"

  caveats <<~EOS
    Sonny.app is not yet signed with an Apple Developer ID, so Gatekeeper
    blocks the first launch. Clear the quarantine flag once after installing:

      xattr -dr com.apple.quarantine /Applications/Sonny.app

    The app bundles its own sonny CLI; `brew install codeprosorg/codepros/sonny`
    puts the CLI on your PATH.
  EOS
end
