# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

cask "sonny-desktop" do
  version "0.11.31"
  sha256 "3f1124e46022140aca197073237cacc184d4aad2e6a2a943121e8e9db7b4b5e8"

  url "https://downloads.codepros.org/sonny/0.11.31/sonny-desktop_0.11.31_darwin_universal.zip"
  name "Sonny"
  desc "Desktop app for the Sonny AI coding agent"
  homepage "https://codepros.org/"

  depends_on macos: ">= :big_sur"

  app "Sonny.app"

  caveats <<~EOS
    Sonny.app is not yet signed with an Apple Developer ID, so Gatekeeper
    blocks the first launch. Clear the quarantine flag once after installing:

      xattr -dr com.apple.quarantine /Applications/Sonny.app

    The app bundles its own sonny CLI; `brew install codeprosorg/codepros/sonny`
    puts the CLI on your PATH.
  EOS
end
