# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

cask "sonny-desktop" do
  version "0.11.30"
  sha256 "31f5cca3afea179b2ac2367cf4b60341d9f06defc554f8ba574ac28f926d3bd9"

  url "https://downloads.codepros.org/sonny/0.11.30/sonny-desktop_0.11.30_darwin_universal.zip"
  name "Sonny"
  desc "Desktop app for the Sonny AI coding agent"
  homepage "https://codepros.org/"

  depends_on macos: ">= :big_sur"

  app "Sonny.app"

  caveats <<~EOS
    Sonny.app is not yet signed with an Apple Developer ID, so Gatekeeper
    blocks the first launch. Clear the quarantine flag once after installing:

      xattr -dr com.apple.quarantine /Applications/Sonny.app

    The app bundles its own sonny CLI; `brew install codeprosorg/codepros/sonny`
    puts the CLI on your PATH.
  EOS
end
