# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NtfyCli < Formula
  desc "TUI client for monitoring ntfy.sh topics"
  homepage "https://gitlab.com/devnw/codepros/oss/ntfy-cli"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  url "https://gitlab.com/devnw/codepros/oss/ntfy-cli/-/jobs/artifacts/v0.3.0/raw/dist/ntfy-cli_0.3.0_darwin_universal.tar.gz?job=goreleaser-release", using: CurlDownloadStrategy
  sha256 "ae8ccfe337be3fe824b6b7c1396adac484c770f6ffbd7ae28f915472c4f467b3"

  def install
    bin.install "ntfy-cli"
  end
end
