# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

class Sonny < Formula
  desc "AI coding agent for the terminal"
  homepage "https://codepros.org/"
  version "0.11.30"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.11.30/sonny_0.11.30_darwin_arm64.tar.gz"
      sha256 "7ba61376fe8307b35015b290d4b8429fb3a12ddc1873a5b8a108790e5e67cc42"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.11.30/sonny_0.11.30_darwin_amd64.tar.gz"
      sha256 "9e98312c9df25e467ef27d5f044868f788b92ef226578ee35e0ab2bc76c2a284"
    end
  end

  on_linux do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.11.30/sonny_0.11.30_linux_arm64.tar.gz"
      sha256 "b95f6b19d5f40f8466178a9d2d1f1d55b786fc36b91cc97825b73ea67a87c96f"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.11.30/sonny_0.11.30_linux_amd64.tar.gz"
      sha256 "0af383d4dc8d71c39dcbad42ae17167b19f6ad6ddf2181060408a6f431482aba"
    end
  end

  def install
    bin.install "sonny"
  end

  test do
    system "#{bin}/sonny", "--version"
  end
end
