# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

class Sonny < Formula
  desc "AI coding agent for the terminal"
  homepage "https://codepros.org/"
  version "0.11.31"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.11.31/sonny_0.11.31_darwin_arm64.tar.gz"
      sha256 "0a9e46ae9cfb241c4a40f604424b95ef06f28617d760e1797aea979b1e7b756f"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.11.31/sonny_0.11.31_darwin_amd64.tar.gz"
      sha256 "ea7034223b65130fa8e3d81bc14dbc286420e3073a49b3573cec146142e55b1b"
    end
  end

  on_linux do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.11.31/sonny_0.11.31_linux_arm64.tar.gz"
      sha256 "39e38b2748ab379756b76cd483d1a4c1ffec1f14900415494d85d81f362e6abb"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.11.31/sonny_0.11.31_linux_amd64.tar.gz"
      sha256 "a4569263a705372f0cdddc7dab4333b02097f226a4ed137c5aa62317944cf313"
    end
  end

  def install
    bin.install "sonny"
  end

  test do
    system "#{bin}/sonny", "--version"
  end
end
