# typed: false
# frozen_string_literal: true

# Generated by the ci-catalog homebrew-publish component
# (gitlab.com/devnw/ci-catalog). DO NOT EDIT: every release overwrites it.

class Sonny < Formula
  desc "AI coding agent for the terminal"
  homepage "https://codepros.org"
  version "0.10.53"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.10.53/sonny_0.10.53_darwin_arm64.tar.gz"
      sha256 "7c005033631e9bce5128a2a7a112347aa73a7732922bb42ca56536d42936b6b6"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.10.53/sonny_0.10.53_darwin_amd64.tar.gz"
      sha256 "9f8ce47aad85a925c421fed1a8513d368881115c7efd7b899a15ecd20bd8d71d"
    end
  end

  on_linux do
    on_arm do
      url "https://downloads.codepros.org/sonny/0.10.53/sonny_0.10.53_linux_arm64.tar.gz"
      sha256 "935c1b7faab956ff2c51d3a948ed59014bb5ce9b8da2eeb258ff1f005f17fc02"
    end
    on_intel do
      url "https://downloads.codepros.org/sonny/0.10.53/sonny_0.10.53_linux_amd64.tar.gz"
      sha256 "ef077f9dc35fc60ad803a3110dc9d76a31f7624df5b172228f4ad95c46b61ce7"
    end
  end

  def install
    bin.install "sonny"
  end

  test do
    system "#{bin}/sonny", "--version"
  end
end
