# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Void < Formula
  desc "DNS sinkhole and local DNS resolver with ad/tracker/malware blocking"
  homepage "https://gitlab.com/devnw/codepros/oss/void"
  version "0.1.18"
  license "Apache-2.0"
  depends_on :macos

  url "https://gitlab.com/devnw/codepros/oss/void/-/jobs/artifacts/v0.1.18/raw/dist/void_0.1.18_darwin_universal.tar.gz?job=goreleaser-release", using: CurlDownloadStrategy
  sha256 "f1a1eff7b71df5715c7acd2591f59e9accd9148a47cbd4212c1119ce12f64750"

  def install
    bin.install "void"
  end

  def caveats
    <<~EOS
      Void has been installed!

      To start the DNS sinkhole:
        sudo void --config /usr/local/etc/void/config.yaml

      Default configuration:
        - Listens on port 53 (UDP/TCP)
        - Forwards to Cloudflare DNS-over-TLS (1.1.1.1, 1.0.0.1)
        - Blocks domains from configured blocklists

      Documentation: https://gitlab.com/devnw/codepros/oss/void
    EOS
  end

  test do
    system "#{bin}/void", "--version"
  end
end
